// Rentals Data - Rental items for events and ceremonies
// =================================================================================

import { DBProduct } from '@/lib/types'

export const rentals: DBProduct[] = [
  {
    id: 'rental-001',
    name: 'Kundulu (32 inches)',
    description: 'Traditional brass Kundulu, 32 inches tall. Small size also available. Perfect for pooja and ceremonies.',
    price_in_cents: 0, // Contact for price
    category: 'rentals',
    image_url: '/images/rentals/kundulu.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rental-002',
    name: 'Ganesh Idol (2 Feet)',
    description: 'Beautiful 2 feet Ganesh idol for religious ceremonies and festivals. Ideal for Ganesh Chaturthi and special poojas.',
    price_in_cents: 0,
    category: 'rentals',
    image_url: '/images/rentals/ganesh-idol.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rental-003',
    name: 'Brass Urli',
    description: 'Traditional brass Urli for floating flowers and diyas. Multiple sizes available. Creates beautiful centerpiece for events.',
    price_in_cents: 0,
    category: 'rentals',
    image_url: '/images/rentals/brass-urli.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rental-004',
    name: 'Brass Diya Urli (Medium)',
    description: 'Medium size brass Diya Urli for traditional lighting. Perfect for weddings, poojas and festival decorations.',
    price_in_cents: 0,
    category: 'rentals',
    image_url: '/images/rentals/brass-diya-urli.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rental-005',
    name: 'German Silver Trays',
    description: 'Elegant German silver trays for serving and decoration. Perfect for weddings, engagements and special occasions.',
    price_in_cents: 0,
    category: 'rentals',
    image_url: '/images/rentals/german-silver-trays.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rental-006',
    name: 'House Warming Decor Dolls',
    description: 'Traditional decor dolls for Griha Pravesh (house warming) ceremonies. Brings auspicious blessings to your new home.',
    price_in_cents: 0,
    category: 'rentals',
    image_url: '/images/rentals/housewarming-dolls.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rental-007',
    name: 'Seemantham Decor Dolls',
    description: 'Beautiful decor dolls for Seemantham (baby shower) ceremonies. Traditional South Indian baby shower decoration.',
    price_in_cents: 0,
    category: 'rentals',
    image_url: '/images/rentals/seemantham-dolls.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rental-008',
    name: 'Mangalasnanam Set',
    description: 'Complete Mangalasnanam set for traditional wedding rituals. Includes all essential items for the sacred bathing ceremony.',
    price_in_cents: 0,
    category: 'rentals',
    image_url: '/images/rentals/mangalasnanam-set.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rental-009',
    name: 'Idli Stand (54 Idlis)',
    description: 'Large idli stand that makes 54 idlis at once. Perfect for parties, events and large gatherings.',
    price_in_cents: 0,
    category: 'rentals',
    image_url: '/images/rentals/idli-stand.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'rental-010',
    name: 'Biryani Handi',
    description: 'Traditional Biryani Handi for authentic dum biryani. Available in small, medium and large sizes.',
    price_in_cents: 0,
    category: 'rentals',
    image_url: '/images/rentals/biryani-handi.jpg',
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]
